"""empty message

Revision ID: 2970290c22e9
Revises: 8705ea781100
Create Date: 2020-04-18 23:07:27.469914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2970290c22e9'
down_revision = '8705ea781100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id_service', sa.Integer(), nullable=False),
    sa.Column('name_service', sa.String(length=20), nullable=True),
    sa.Column('service_time', sa.String(length=20), nullable=True),
    sa.Column('prise_service', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_service')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service')
    # ### end Alembic commands ###
