"""empty message

Revision ID: 8705ea781100
Revises: c5d93edbd0dc
Create Date: 2020-03-05 16:33:58.829792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8705ea781100'
down_revision = 'c5d93edbd0dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id_service', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name_service', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('service_time', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('prise_service', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_service', name='service_pkey')
    )
    # ### end Alembic commands ###
