"""empty message

Revision ID: c5d93edbd0dc
Revises: ffe2bed22b64
Create Date: 2020-02-29 18:41:48.952014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d93edbd0dc'
down_revision = 'ffe2bed22b64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id_service', sa.Integer(), nullable=False),
    sa.Column('name_service', sa.String(length=20), nullable=True),
    sa.Column('service_time', sa.String(length=20), nullable=True),
    sa.Column('prise_service', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_service')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service')
    # ### end Alembic commands ###
